apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-flask-app  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-flask-app
  minReplicas: 1
  maxReplicas: 10  
  targetCPUUtilizationPercentage: 50  
