pipeline {
    environment {
        registry = "hackcoderr/flask:latest" 
        registryCredential = 'docker-cred'
        dockerImage = ''
    }
    agent any
    }

    stages {
        stage('Build Image') { 
            steps { 
                script { 
                    dockerImage = docker.build registry  
                }
            } 
        }
        stage('Push Image') { 
            steps { 
                script { 
                    docker.withRegistry( '', registryCredential ) { 
                        dockerImage.push() 
                    }
                } 
            }
        }
    }
}
