pipeline {
    environment {
        registry = "hackcoderr/flask:latest" 
        dockerImage = ''
    }
    agent any
    }

    stages {
        stage('Build Image') { 
            steps { 
                script { 
                    dockerImage = docker.build registry  
                }
            } 
        }
    }
}
