pipeline {
    environment {
        registry = "hackcoderr/flask" 
        registryCredential = 'docker-cred'
        dockerImage = ''
    }
    agent any

    stages {
        stage('Build Image') { 
            steps { 
                script { 
                    dockerImage = docker.build registry  
                }
            } 
        }
        stage('Push Image') { 
            steps { 
                script { 
                    docker.withRegistry( '', registryCredential ) { 
                        dockerImage.push() 
                    }
                } 
            }
        }
        stage('Deployment') {
            steps {
                sh 'kubectl apply -f deployment.yaml'
                sh 'kubectl kubectl apply -f svc.yaml'
            }
        }
    }
}
